
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dengjk?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true






