server:
  port: 9095

spring:
  thymeleaf:
    #设置响应类型accountInfo.html
    content-type: text/html
      #所在路径
    prefix: classpath:/templates/
    #文件后缀名
    suffix: .html
    #关闭缓存
    cache: false
    #html5引擎 需要导入nekohtml依赖
    mode: LEGACYHTML5
  profiles:
    active: db









